from __future__ import annotations

DISTRIBUTION_NAME = "knowlume"
REPOSITORY_URL = "https://github.com/yjdy/Knowlume"
PYPI_JSON_URL = f"https://pypi.org/pypi/{DISTRIBUTION_NAME}/json"

OBJECT_CONTRACT_VERSION = 2
READABLE_OBJECT_CONTRACT_RANGE = (2, 2)
WRITABLE_OBJECT_CONTRACT_RANGE = (2, 2)
LOCATOR_VERSION = 2
RELATION_SCHEMA_VERSION = 2
INTERFACE_VERSION = 1
PROJECTION_VERSION = 2
PARSER_VERSION = 1

SUPPORTED_PYTHON_MIN = (3, 13)
SUPPORTED_PYTHON_MAX_EXCLUSIVE = (3, 15)
